version: "3.8"

services:

  discovery-server:
    container_name: discovery-server
    image: rupesh1997/discovery-server:1.0.0
    ports:
      - '8761:8761'
    networks:
      - microservices-devops
    restart: always

#  chat-service:
#    container_name: chat-service
#    image: rupesh1997/chat-service:1.0.0
#    ports:
#      - '9393:9393'
#    networks:
#      - microservices-devops
#    restart: always

#  config-service:
#    container_name: config-service
#    image: rupesh1997/config-service:1.0.0
#    ports:
#      - '8888:8888'
#    networks:
#      - microservices-devops
#    restart: always

#  gateway-service:
#    container_name: gateway-service
#    image: rupesh1997/gateway-service:1.0.0
#    ports:
#      - '8687:8687'
#    networks:
#      - microservices-devops

#  frontend:
#    container_name: frontend
#    image: rupesh1997/frontend:latest
#    ports:
#      - "8080:80"
#    networks:
#      - microservices-devops
#    depends_on:
#      - gateway-service
#    restart: always

networks:
  microservices-devops:
    driver: bridge
