server:
  port: 8687

spring:
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 60s
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

#EUREKA/DISCOVERY-SERVER CONFIGURATION
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    hostname: discovery-server

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    enabled: true

info:
  app:
    name: gateway-service
  version: 1.0.0
  description: This service acts as a gateway for the microservices application.